  -- 1. 创建 notes 表
  CREATE TABLE notes (
    id bigint generated by default as identity primary key,
    title text not null,
    summary text,
    content_md text,
    tags jsonb default '[]'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
  );

  -- 2. 创建 journals 表
  CREATE TABLE journals (
    id bigint generated by default as identity primary key,
    title text not null,
    excerpt text,
    content_html text,
    content_json text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
  );

  -- 3. 创建 hobbies 表
  CREATE TABLE hobbies (
    id bigint generated by default as identity primary key,
    title text not null,
    type text not null,
    status text not null,
    rating smallint,
    review text,
    cover_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
  );

  -- 4. 创建 todos 表
  CREATE TABLE todos (
    id uuid default gen_random_uuid() primary key,
    text text not null,
    completed boolean default false not null,
    user_id uuid references auth.users(id) on delete cascade not null,
    priority text default 'medium',
    start_date date,
    due_date date,
    status text default 'pending',
    completed_at timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );

  -- 5. 创建 checkins 表
  CREATE TABLE checkins (
    user_id uuid primary key references auth.users(id) on delete cascade not null,
    last_date date,
    streak integer default 0 not null,
    total_count integer default 0 not null,
    last_record text
  );

  -- 6. 创建 announcements 表
  CREATE TABLE announcements (
    id uuid default gen_random_uuid() primary key,
    text text not null,
    type text default 'info' not null,
    user_id uuid references auth.users(id) on delete set null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );

  -- 启用所有表的 RLS
  ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
  ALTER TABLE journals ENABLE ROW LEVEL SECURITY;
  ALTER TABLE hobbies ENABLE ROW LEVEL SECURITY;
  ALTER TABLE todos ENABLE ROW LEVEL SECURITY;
  ALTER TABLE checkins ENABLE ROW LEVEL SECURITY;
  ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;

  -- Notes 权限策略
  CREATE POLICY "Public notes viewable by everyone" ON notes FOR SELECT USING (true);
  CREATE POLICY "Auth insert notes" ON notes FOR INSERT TO authenticated WITH CHECK (true);
  CREATE POLICY "Auth update notes" ON notes FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
  CREATE POLICY "Auth delete notes" ON notes FOR DELETE TO authenticated USING (true);

  -- Journals 权限策略
  CREATE POLICY "Public journals viewable by everyone" ON journals FOR SELECT USING (true);
  CREATE POLICY "Auth insert journals" ON journals FOR INSERT TO authenticated WITH CHECK (true);
  CREATE POLICY "Auth update journals" ON journals FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
  CREATE POLICY "Auth delete journals" ON journals FOR DELETE TO authenticated USING (true);

  -- Hobbies 权限策略
  CREATE POLICY "Public hobbies viewable by everyone" ON hobbies FOR SELECT USING (true);
  CREATE POLICY "Auth insert hobbies" ON hobbies FOR INSERT TO authenticated WITH CHECK (true);
  CREATE POLICY "Auth update hobbies" ON hobbies FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
  CREATE POLICY "Auth delete hobbies" ON hobbies FOR DELETE TO authenticated USING (true);

  -- Todos 权限策略 (仅限所属用户)
  CREATE POLICY "Users can view their own todos" ON todos FOR SELECT TO authenticated USING (auth.uid() = user_id);
  CREATE POLICY "Users can insert their own todos" ON todos FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
  CREATE POLICY "Users can update their own todos" ON todos FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  CREATE POLICY "Users can delete their own todos" ON todos FOR DELETE TO authenticated USING (auth.uid() = user_id);

  -- Checkins 权限策略 (仅限所属用户)
  CREATE POLICY "Users can view their own checkins" ON checkins FOR SELECT TO authenticated USING (auth.uid() = user_id);
  CREATE POLICY "Users can insert their own checkins" ON checkins FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
  CREATE POLICY "Users can update their own checkins" ON checkins FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  CREATE POLICY "Users can delete their own checkins" ON checkins FOR DELETE TO authenticated USING (auth.uid() = user_id);

  -- Announcements 权限策略 (所有人可见，仅登录用户可管理)
  CREATE POLICY "Public announcements viewable by everyone" ON announcements FOR SELECT USING (true);
  CREATE POLICY "Auth insert announcements" ON announcements FOR INSERT TO authenticated WITH CHECK (true);
  CREATE POLICY "Auth update announcements" ON announcements FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
  CREATE POLICY "Auth delete announcements" ON announcements FOR DELETE TO authenticated USING (true);
