-- 1. 创建 notes 表
CREATE TABLE notes (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  content_md text,
  tags jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 创建 journals 表
CREATE TABLE journals (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text,
  content_html text,
  content_json text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 创建 hobbies 表
CREATE TABLE hobbies (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null,
  status text not null,
  rating smallint,
  review text,
  cover_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. 启用 Row Level Security (RLS)
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE journals ENABLE ROW LEVEL SECURITY;
ALTER TABLE hobbies ENABLE ROW LEVEL SECURITY;

-- 5. 配置 Notes 权限策略
-- 所有人都可以读取
CREATE POLICY "Public profiles are viewable by everyone."
  ON notes FOR SELECT
  USING ( true );

-- 只有登录用户（博主）可以新增/修改/删除
CREATE POLICY "Users can insert their own notes."
  ON notes FOR INSERT
  TO authenticated
  WITH CHECK ( true );

CREATE POLICY "Users can update their own notes."
  ON notes FOR UPDATE
  TO authenticated
  USING ( true )
  WITH CHECK ( true );

CREATE POLICY "Users can delete their own notes."
  ON notes FOR DELETE
  TO authenticated
  USING ( true );

-- 6. 配置 Journals 权限策略
CREATE POLICY "Public journals viewable by everyone" ON journals FOR SELECT USING (true);
CREATE POLICY "Auth insert journals" ON journals FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update journals" ON journals FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Auth delete journals" ON journals FOR DELETE TO authenticated USING (true);

-- 7. 配置 Hobbies 权限策略
CREATE POLICY "Public hobbies viewable by everyone" ON hobbies FOR SELECT USING (true);
CREATE POLICY "Auth insert hobbies" ON hobbies FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update hobbies" ON hobbies FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Auth delete hobbies" ON hobbies FOR DELETE TO authenticated USING (true);
